### ISSUE TITLE
Chunk 6.3 - Book list

### ISSUE THREAD

**Issue by dossorio** [dossorio/google-interview-university#32]
Book list 
  - [x] Computer Architecture https://github.com/jwasham/google-interview-university#computer-architecture
  - [x] Language Specific https://github.com/jwasham/google-interview-university#language-specific
  - [x] Optional Books https://github.com/jwasham/google-interview-university#optional-books

**Comment by eduardomontalvo** [comment]
Hola dossorio, me gustaría ayudar en el proyecto de la traducción. ¿Llevan algún orden?

**Comment by dossorio** [comment]
Hola @eduardomontalvo !

Si las issues que ves abiertas y que nadie ha comentado en ellas están todavía por traducir, siguen el order del índice principal, así que feel free to pick any issue and start translating !! :)

Solo comenta, en la issue que quieres hacer diciendo que te encargas de ella.

Mil gracias !!

**Comment by dossorio** [comment]
Hi @eduardomontalvo ! 

How is it going ? Please have a look at this instructions https://github.com/jwasham/google-interview-university/pull/78#issue-196754356 they might help.

Let me know if you need a hand with anything.

Happy translating !

**Comment by eduardomontalvo** [comment]
I will handle this chunk! @dossorio :)

**Comment by esaucedof** [comment]
Done
